from .cartitems import CartItems
from .cartitemscrud import CartItemDelete
from .createorderitem import CreateOrderItem
from .managerlist import ManagerList
from .managerrole import ManagerRole
from .menuitemcreate import MenuItemCreate
from .menuitemretrive import MenuItemRetrive
from .menulist import MenuList
from .menulistmodify import MenuListModify
from .orderdeliverby import OrderDeliverBy
from .orderdetail import OrderDetails
from .orderlist import OrderList
from .placeorder import PlaceOrder
from .userdetail import UserDetail
from .userlist import UserList
from .menulistmodify import MenuListModify
from .ContactDetails import ContactDetailsView
