# Generated by Django 4.1.5 on 2023-01-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_remove_order_order_details_orderitem_order_details2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_details2',
        ),
        migrations.AddField(
            model_name='order',
            name='all_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_orders', to='LittleLemonDRF.orderitem'),
        ),
    ]
