# Generated by Django 4.1.5 on 2023-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0004_orderitem_unit_price_alter_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
