# Generated by Django 4.1.5 on 2023-01-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0004_alter_cart_unit_price_alter_order_all_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aa_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_data', to='LittleLemonDRF.cart'),
        ),
    ]
