# Generated by Django 4.1.5 on 2023-01-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0005_order_aa_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
