# Generated by Django 4.1.5 on 2023-01-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0006_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_details',
            field=models.ManyToManyField(blank=True, null=True, to='LittleLemonDRF.order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='categorey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='LittleLemonDRF.categorey'),
        ),
    ]
