# Generated by Django 4.1.5 on 2023-01-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0007_orderitem_order_details_alter_menuitem_categorey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_details',
        ),
    ]
