# Generated by Django 4.1.5 on 2023-01-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0008_remove_orderitem_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LittleLemonDRF.cart'),
        ),
    ]
