# Generated by Django 4.1.5 on 2023-01-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0011_rename_order_orderitem_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='cart',
        ),
    ]
